security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        database_users:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users
            form_login:
                login_path: login
                check_path: login
                username_parameter: email
                password_parameter: password
            logout:
                path: /logout
                target: /

            entry_point: App\Security\AccessDeniedRedirectHandler

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
